### ISSUE TITLE
tests are not getting closed in azure and as a result the page crashes...

### ISSUE THREAD

**Issue by ilanmg** [christian-draeger/basic-selenium-project#4]
Hi Christian,
i downloaded your project and it looks awsome.
i'm having problems with running my tests in azure - does your project support this end to end? 
the problem is that when i'm running my tests in remote the tests are not getting closed for some reason  and as a result the page crashes...can you please tell how your tests run in remote in azure?

Thanks
Ilan

**Comment by christian-draeger** [comment]
hi @ilanmg ,
me personally have no experience with azure and therefore never tried to run it in azure.
I'll have a look if i can find something potential fishy when instantiating / stopping the driver.

As far as i know it is possible to get a free azure trial - so i will try to get it running over there in the next few days and keep you updated.

**Comment by christian-draeger** [comment]
i refactored the project a little bit. could you please try again

**Comment by christian-draeger** [comment]
since there have been a complete rewrite of the project i'm going to close this
